name: Deploy

on:
  push:
    branches:
    - stable
  workflow_dispatch:

jobs:
  deploy:
    environment: server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install Nix
      uses: DeterminateSystems/determinate-nix-action@v3.14.0
    - name: Setup SSH access
      uses: webfactory/ssh-agent@v0.9.1
      with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
    - name: Colmena Apply
      run: nix run .#colmena -- apply --on pawhost-next
