name: Reset-next

on:
  workflow_dispatch:

jobs:
  reset:
    environment: server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install Nix
      uses: DeterminateSystems/determinate-nix-action@v3.15.0
    - name: Setup SSH access
      uses: webfactory/ssh-agent@v0.9.1
      with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
    - name: Kaboom
      env:
        SSH_KEY: ${{secrets.SSH_KEY}}
      run: |
        cd init
        nix run nixpkgs#nixos-anywhere -- --flake .#pawhost-next -p 666 cicd@77.90.16.190
